 # spring.datasource.url=jdbc:h2:file:./data/pagamdb
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/pagamdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=11221999

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Optimisation Hibernate
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.open-in-view=false

# Désactiver H2 inutile
spring.h2.console.enabled=false

# Configuration Gmail (ou ton propre serveur SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sadikhyade851@gmail.com
# spring.mail.password=Q-v4ry!AQ,b5>dU
spring.mail.password=azkqpahketqmfzff
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.from=sadikhyade851@gmail.com
spring.mail.default-encoding=UTF-8


# App port (optionnel)
server.address=0.0.0.0
server.port=8086

# JWT secrets & expiration (à configurer plus tard)
jwt.secret=MaSuperCleSecreteDeJWTQuiFaitAuMoins32Caracteres!
jwt.expiration=3600000

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

logging.level.org.springframework.security=DEBUG

#Implementation de la cle de meteo
openweathermap.api.key=91a421e86c57cd1309cb65e78e8d673a

spring.web.resources.static-locations=classpath:/static/,file:uploads/




